### ISSUE TITLE
Error with Postgresql

### ISSUE THREAD

**Issue by towjokinen** [yedidiaklein/moodle-local_aiquestions#1]
Tryin to get this going but having issue with postgresql. 

Adhoc task failed: local_aiquestions\task\questions,Error writing to database (ERROR:  syntax error at or near "user"
LINE 1: ...ERT INTO mdl_local_aiquestions (course,numoftries,user,tries...
                                                             ^
INSERT INTO mdl_local_aiquestions (course,numoftries,user,tries,uniqid,gift,success) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id
[array (
  'course' => 26,
  'numoftries' => '10',
  'user' => '43',
  'tries' => 0,
  'uniqid' => '436464a1c53cd337.11000101',
  'gift' => '',
  'success' => '',
)])
Debug info:
ERROR:  syntax error at or near "user"
LINE 1: ...ERT INTO mdl_local_aiquestions (course,numoftries,user,tries...

The error message suggests that there is a syntax error in your PostgreSQL query. The keyword "user" is causing the issue because it is a reserved keyword in PostgreSQL.

Any suggestions ?

**Comment by yedidiaklein** [comment]
tnx, I will change the field name.. and will update

**Comment by yedidiaklein** [comment]
fixed
