### ISSUE TITLE
Unhelpful link in message to user of plugin?

### ISSUE THREAD

**Issue by wichmann** [yedidiaklein/moodle-local_aiquestions#11]
Hello,

I like your plugin and it is working fine. I just translated the strings into German and thought about one of the messages: 

> The cron task seems not to run, questions generation rely on AdHoc Tasks that are created by the cron task, please check your cron settings. See <a href="https://docs.moodle.org/en/Cron#Setting_up_cron_on_your_system"> https://docs.moodle.org/en/Cron#Setting_up_cron_on_your_system</a> for more information.
[Source](https://github.com/yedidiaklein/moodle-local_aiquestions/blob/5d4e58578adee6abb43e4e463ef56be69aae4769/lang/en/local_aiquestions.php#L81)

Wouldn't it be more helpful for users to hint at the administrator of the site to fix the problem instead of providing the given URL? A normal user may not know what a cron is and what to do in this case?!

Best regards,
    Christian

**Comment by wilenius** [comment]
Yeah you're right, but this message won't be displayed on a properly configured site anyway. It's meant for private test installations, I'd argue, and in those cases the user and the administrator are the same person...

**Comment by wichmann** [comment]
Thanks for your response.

You are right. Since the message is only shown if the plugin is not configured correctly it wouldn't be a problem.
